#!/usr/bin/env python3
"""
DevOps AI Agent — main entry point.

Usage:
    python agent/main.py --file examples/nginx_failure.json
    python agent/main.py --file examples/high_cpu_incident.json --output reports/incident-analysis.md
    python agent/main.py --file examples/db_connection_error.json --no-ai
"""

import argparse
import json
import logging
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# Ensure the agent directory is on the path so sibling imports work regardless
# of the working directory from which the script is invoked.
sys.path.insert(0, str(Path(__file__).parent))

from schemas import Incident, AnalysisResult, AnalysisMode
import incident_analyzer
import runbook_engine
import ai_interface

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%SZ",
)
logger = logging.getLogger("devops-agent")

DEFAULT_REPORT_PATH = Path(__file__).parent.parent / "reports" / "incident-analysis.md"


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def load_incident(file_path: str) -> Incident:
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"Incident file not found: {file_path}")

    with open(path, "r", encoding="utf-8") as fh:
        data = json.load(fh)

    return Incident(
        title=data.get("title", "Unnamed Incident"),
        description=data.get("description", ""),
        service=data.get("service", "unknown"),
        environment=data.get("environment", "unknown"),
        timestamp=data.get("timestamp", datetime.now(timezone.utc).isoformat()),
        logs=data.get("logs", []),
        metrics=data.get("metrics", {}),
        tags=data.get("tags", []),
        raw=data,
    )


def render_report(incident: Incident, result: AnalysisResult, file_path: str) -> str:
    lines = [
        "# DevOps AI Agent — Incident Analysis Report",
        "",
        f"> Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        f"> Analysis mode: **{result.analysis_mode.value}**",
        f"> Confidence score: **{result.confidence_score:.0%}**",
        "",
        "---",
        "",
        "## Incident Summary",
        "",
        f"| Field       | Value |",
        f"|-------------|-------|",
        f"| **Title**   | {incident.title} |",
        f"| **Service** | {incident.service} |",
        f"| **Env**     | {incident.environment} |",
        f"| **Time**    | {incident.timestamp} |",
        f"| **Source**  | `{file_path}` |",
        "",
        "---",
        "",
        "## Analysis Results",
        "",
        f"### Severity: `{result.severity.value}`",
        "",
        "### Root Cause",
        "",
        result.root_cause,
        "",
        "### Recommended Fix",
        "",
        result.recommended_fix,
        "",
        "### Detected Categories",
        "",
    ]

    if result.detected_categories:
        for cat in result.detected_categories:
            lines.append(f"- `{cat.replace('_', ' ').title()}`")
    else:
        lines.append("- No specific category detected — manual investigation required.")

    lines += [
        "",
        "---",
        "",
        "## Runbook Steps",
        "",
    ]

    for step in result.runbook_steps:
        if step.startswith("\n---"):
            lines.append("")
            lines.append(step.strip())
            lines.append("")
        else:
            lines.append(step)

    if result.ai_insights:
        lines += [
            "",
            "---",
            "",
            "## AI Expert Insights",
            "",
            result.ai_insights,
            "",
        ]

    lines += [
        "",
        "---",
        "",
        "## Incident Metrics Snapshot",
        "",
        "| Metric | Value |",
        "|--------|-------|",
    ]

    for key, val in incident.metrics.items():
        lines.append(f"| `{key}` | {val} |")

    lines += [
        "",
        "---",
        "",
        "## Recent Log Entries",
        "",
        "```",
    ]
    lines.extend(incident.logs[-10:])
    lines += [
        "```",
        "",
        "---",
        "",
        "*Report generated by DevOps AI Agent — Task 10*",
        "",
    ]

    return "\n".join(lines)


def print_summary(incident: Incident, result: AnalysisResult) -> None:
    separator = "=" * 60
    print(f"\n{separator}")
    print(f"  DevOps AI Agent — Incident Analysis")
    print(separator)
    print(f"  Incident  : {incident.title}")
    print(f"  Service   : {incident.service}  [{incident.environment}]")
    print(f"  Severity  : {result.severity.value}")
    print(f"  Mode      : {result.analysis_mode.value}")
    print(f"  Confidence: {result.confidence_score:.0%}")
    print(f"  Categories: {', '.join(result.detected_categories) or 'none'}")
    print(separator)
    print(f"\nRoot Cause:\n  {result.root_cause}\n")
    print(f"Recommended Fix:\n  {result.recommended_fix}\n")
    print(f"Runbook Steps ({len([s for s in result.runbook_steps if not s.startswith(chr(10))])} steps):")
    for step in result.runbook_steps:
        if step.startswith("\n---"):
            print(f"\n  {step.strip()}")
        else:
            print(f"  {step}")
    if result.ai_insights:
        print(f"\nAI Insights:\n  {result.ai_insights}")
    print(f"\n{separator}\n")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="DevOps AI Agent — analyze incidents, logs, and metrics",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python agent/main.py --file examples/nginx_failure.json
  python agent/main.py --file examples/high_cpu_incident.json --output reports/custom.md
  python agent/main.py --file examples/db_connection_error.json --no-ai
        """,
    )
    parser.add_argument(
        "--file", "-f",
        required=True,
        help="Path to the incident JSON file",
    )
    parser.add_argument(
        "--output", "-o",
        default=str(DEFAULT_REPORT_PATH),
        help=f"Output path for the Markdown report (default: {DEFAULT_REPORT_PATH})",
    )
    parser.add_argument(
        "--no-ai",
        action="store_true",
        help="Disable AI enhancement even if ANTHROPIC_API_KEY is set",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose logging",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    # 1. Load incident
    try:
        logger.info("Loading incident from: %s", args.file)
        incident = load_incident(args.file)
    except (FileNotFoundError, json.JSONDecodeError) as exc:
        logger.error("Failed to load incident file: %s", exc)
        return 1

    # 2. Rule-based analysis
    logger.info("Running rule-based analysis…")
    result = incident_analyzer.analyze(incident)

    # 3. Attach runbook steps
    result.runbook_steps = runbook_engine.get_runbook_steps(result.detected_categories)

    # 4. Optionally enhance with AI
    if not args.no_ai:
        result = ai_interface.enhance_analysis(incident, result)
    else:
        logger.info("AI enhancement disabled via --no-ai flag.")

    # 5. Print summary to console
    print_summary(incident, result)

    # 6. Write report
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    report_content = render_report(incident, result, args.file)
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(report_content)

    logger.info("Report written to: %s", output_path)
    print(f"[OK] Report saved to: {output_path}\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
