"""
Report generator: produces a Markdown security report from scanner findings.
"""

import os
from datetime import datetime, timezone
from pathlib import Path
from collections import defaultdict


SEVERITY_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}
SEVERITY_BADGE = {
    "CRITICAL": "🔴 CRITICAL",
    "HIGH":     "🟠 HIGH",
    "MEDIUM":   "🟡 MEDIUM",
    "LOW":      "🔵 LOW",
}


def _severity_sort_key(finding: dict) -> int:
    return SEVERITY_ORDER.get(finding.get("severity", "LOW"), 99)


def _count_by_severity(findings: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = defaultdict(int)
    for f in findings:
        counts[f.get("severity", "LOW")] += 1
    return counts


def generate_markdown(findings: list[dict], output_path: str, scan_path: str) -> str:
    """
    Generate a Markdown security report and write it to output_path.
    Returns the path of the written report.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    sorted_findings = sorted(findings, key=_severity_sort_key)
    counts = _count_by_severity(findings)
    total = len(findings)

    lines = []

    # ---- Header ----
    lines += [
        "# Infrastructure Security Scanner Report",
        "",
        f"**Scan Date:** {now}  ",
        f"**Target Path:** `{scan_path}`  ",
        f"**Total Findings:** {total}",
        "",
        "---",
        "",
    ]

    # ---- Executive Summary ----
    lines += [
        "## Executive Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ]
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
        badge = SEVERITY_BADGE[sev]
        lines.append(f"| {badge} | {counts.get(sev, 0)} |")

    lines += ["", "---", ""]

    if not findings:
        lines += [
            "## Findings",
            "",
            "> No security issues detected. All analysed configuration files appear clean.",
            "",
        ]
    else:
        # ---- Findings grouped by file ----
        lines += ["## Findings", ""]

        by_file: dict[str, list[dict]] = defaultdict(list)
        for f in sorted_findings:
            by_file[f["file"]].append(f)

        for fpath, file_findings in sorted(by_file.items()):
            fname = Path(fpath).name
            lines += [
                f"### `{fname}`",
                f"> File: `{fpath}`",
                "",
            ]
            for idx, finding in enumerate(file_findings, start=1):
                badge = SEVERITY_BADGE.get(finding["severity"], finding["severity"])
                lines += [
                    f"#### Finding {idx}: {finding['title']}",
                    "",
                    f"**Severity:** {badge}  ",
                    f"**File:** `{finding['file']}`",
                    "",
                    f"**Explanation:**  ",
                    f"{finding['explanation']}",
                    "",
                    f"**Remediation:**  ",
                    f"{finding['remediation']}",
                    "",
                    "---",
                    "",
                ]

    # ---- Footer ----
    lines += [
        "## Scan Coverage",
        "",
        "| File Type | Description |",
        "|-----------|-------------|",
        "| `.yml` / `.yaml` | Docker Compose and Kubernetes manifests |",
        "| `.tf` | HashiCorp Terraform configurations |",
        "| `.env` | Environment variable files |",
        "",
        "---",
        "",
        "_Report generated by **Infrastructure Security Scanner** — a portfolio project._",
        "",
    ]

    report_content = "\n".join(lines)

    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(report_content)

    return output_path
